services:
  database:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    healthcheck:
      test: [ "CMD", "mongosh", "--username", "${DB_USER}", "--password", "${DB_PASSWORD}", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  web-app:
    build: .
    # הפורטים החוצה הוסרו! הגישה תהיה רק דרך Nginx הפנימי
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - MONGO_URI=mongodb://${DB_USER}:${DB_PASSWORD}@database:27017/${DB_NAME}?authSource=admin
    depends_on:
      database:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # חשיפת שרת האינטרנט לעולם בפורט 80 הסטנדרטי
    volumes:
      # הזרקת קובץ ההגדרות שלנו לתוך נתיב ההגדרות המובנה של Nginx בקונטיינר
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-app # מוודא ש-Nginx יעלה רק אחרי שהאפליקציה מוכנה לקבל בקשות
